version: "3.8"
services:
    database:
        container_name: tt_database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        cap_add:
            - SYS_NICE
        volumes:
            - mysqlbdvol:/var/lib/mysql
        ports:
            - "3307:3306"
    php:
        container_name: tt_php
        build:
            context: ./php
        ports:
            - '9001:80'
        restart: always
        volumes:
            - ./app:/var/www/app
        depends_on:
            - database
    nginx:
        container_name: tt_nginx
        image: nginx:stable-alpine
        ports:
            - '8008:80'
        restart: always 
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - database
    phpmyadmin:
        container_name: tt_phpmyadmin
        image: phpmyadmin
        restart: always
        environment:
            PMA_HOSTS: database
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - '8090:80'

volumes:
    mysqlbdvol: