homepage:
    path: /
    controller: App\Controller\TeamController::index

dashboard:
    path: /dashboard
    controller: App\Controller\PlayerController::dashboard


controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

